### ISSUE TITLE
Inventory Item search

### ISSUE THREAD

**Issue by ThomasW0221** [spamntaters/foodBankAngular#24]
When searching inventory items, search should be "fuzzy". I believe best way to achieve this is instead of having a submit button, we just have an onchange event that makes a regex out of whatever is in the search field and compares it to each inventory item being held in the list of returned query results.
Something like what is below...

onChangeEvent => (term) => {
     dsHoldingQueryResults.filter( item.match(term) === true)
}

**Comment by spamntaters** [comment]
done by @cmalang
