### ISSUE TITLE
Page Not Found on Chrome (possibly other browsers too though)

### ISSUE THREAD

**Issue by ThomasW0221** [spamntaters/foodBankAngular#25]
When refreshing the donation page (Nicolas also says that it happens on the other pages), sometimes a page-not-found error is returned. I believe this is specific to the front-end and does not involve the back-end components. Possible Angular routing issue? The hosting site you are using may also have logs for it.

**Comment by spamntaters** [comment]
This is an issue with Netlify redirect rules, I'll have to do some googling

**Comment by spamntaters** [comment]
It only happens when you try to force browse to the pages (e.g. you enter foodbank.ml/donations into the address bar)

**Comment by ThomasW0221** [comment]
I still think we need to look into a solution for this. If someone from the pantry is sitting on the donation page and they decide to refresh it for whatever reason, the donation page should be reloaded instead of a "page not found" showing up

**Comment by ThomasW0221** [comment]
I believe this has been resolved so I will close this issue.
