### ISSUE TITLE
Statistics Promotion

### ISSUE THREAD

**Issue by ThomasW0221** [spamntaters/foodBankAngular#44]
When you have time, test code on st-12 branch. After you have done this, make any styling changes you may feel are necessary (its basically just all tacked in their in rows), and then promote the changes up to dev then master. 

If you can, it would be best if this was done by no later then 12:00 pm tomorrow so we can make sure everything is squared away for the demo

**Comment by spamntaters** [comment]
All done! @ThomasW0221. Merged to master.
